[features]
seeds = false
skip-lint = false
[programs.localnet]
solagram_db = "986HMwKkWJRdF15ywXYaMJX1sqV14psxoon7hZ43Mtm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/echo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
